### ISSUE TITLE
Persisting Powershell variables between steps

### ISSUE THREAD

**Issue by MiguelAlho** [Microsoft/vso-agent-tasks#375]
Is it possible to define (environment or global) variables in a powershell build step, and be able to use it in another (powershell) step further ahead?

I've been trying to do this, for instance, in a step where a set a variable for the package version by running GitVersion, and then further on, after running the build and tests, tag my repo. The script where I run the tagging step can't get the value of the variable I previously set.

Any recomendations?

Thanks!

**Comment by chrisrpatterson** [comment]
You can use the following command by simply writing it to standard out (Write-Host) in powershell

 ##vso[task.setvariable variable=testvar;]testvalue

This will make the variable available later in the build and it should be in your environment.  We have a behavior change coming in the next deployment (Early September) that will late bind variables references in inputs so you could set a variable in one task and then use it in an input via the $(testvar) syntax and the replacement will happen as expected.

**Comment by MiguelAlho** [comment]
thanks!

unfortunately, I'm using TFS 2015 and that suggestion doesn't seem to work or i'm completely doing it wrong. As a workaround, I'm persisting the values to file and reading from the file in the steps ahead. I'll change that when late binding becomes available!

**Comment by adriaanthomas** [comment]
@chrisrpatterson is it possible to give an indication when exactly "Early September" is?

We'd like to use the behaviour change you mention to deploy to a site / slot specifically for a branch. We have a PowerShell script that determines the correct name and calls `Write-Host` to create a new variable, and would like to use this as input for our deployment task...

**Comment by npenin** [comment]
@chrisrpatterson Will it happen in TFS on premise ?

**Comment by chrisrpatterson** [comment]
It is in 2015 Update 1

**Comment by npenin** [comment]
2015 update 1 is available only in english, but our TFS has been installed in French :(

**Comment by chrisrpatterson** [comment]
It is currently only in CTP and we don’t localize those.  At RTM you will be able to get it in french.

**Comment by damienpontifex** [comment]
> This will make the variable available later in the build and it should be in your environment. We have a behavior change coming in the next deployment (Early September) that will late bind variables references in inputs so you could set a variable in one task and then use it in an input via the $(testvar) syntax and the replacement will happen as expected.

@chrisrpatterson has this happened? And is there any documentation on using it?

**Comment by chrisrpatterson** [comment]
https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md you can see the list of commands you can use from scripts.  you want task.setvariable

**Comment by MiguelAlho** [comment]
Can a variable defined in a script (using the technique above) be used in the Repository tab's "Label Format" input? 

I've defined a GitVersionTag variable, set in a script using:

`Write-Host ##vso[task.setvariable variable=GitVersionTag;]$VersionString`

Will the Label Format input late bind to this? My current run tags the repo with the "$(GitVersionTag)" text and not the value.

**Comment by MiguelAlho** [comment]
Figured it out! By setting the updateBuildnunmber variable:

`Write-Host ("##vso[build.updatebuildnumber]$versionToSet")`

in the initial script (that's doing a few things other than just getting the version, such as updating assemblyInfo and nuspecs), I can then use $(build.buildNumber) in the Label Format input in the repository tab to tag the repo correctly!

**Comment by MylesArkell** [comment]
We have VSO 2015 on prem and just upgraded to update 1, however I have not been able to get this to work. Some people have commented that it was fixed in update 1. Has anyone been able to verify this?

Or am I doing something wrong?
##vso[task.setvariable variable=featurePackageName;]$targetNupkg
Write-Host "featurePackageName: "$Env:featurePackageName

the value shows up empty?

**Comment by ericsciple** [comment]
@MylesArkell In your task/script, you would emit "##vso[task.setvariable variable=featurePackageName;]SomeValue" over STDOUT - if using ps1 script then this could be from unintercepted output or explicit Write-Host calls. If you immediately, check the value of $env:featurePackageName, then the value wouldn't be set. However if you check it in the next task that runs, then the value would be set. Does that help?

**Comment by MylesArkell** [comment]
@ericsciple thank you very much for your quick reply Eric, I understand now and yes that works perfectly.
I have rewritten it as 
Write-Host ("##vso[task.setvariable variable=featurePackageName;]$targetNupkg")

and this is indeed available in future tasks! Fantastic

**Comment by tanyabr** [comment]
Hi guys, 

Any idea how can I make this value available not only in the next task as a simple variable, but as a variable I can use in 'Powershell on target machines' task as the machine to connect to?
What I need is to determine dynamically the machine I'm going to perform the next task on. Now I know how to return the machine name to the environment, but still can't use it as the parameter needed to  'Powershell on target machines' task.

I'll be glad to any possible ideas and assistance...

**Comment by pversteijnen** [comment]
Is it possible to use the variable as input on another task? So not using it directly in the ps1 of another task but pass that to another task using a parameter. What format should I use? Now I get the string I fill in and not the value.

This is what I use in my ps1: Write-Host ("##vso[task.setvariable variable=$MachineVariableToSet;]$($machine.name)")
This is what I pass allong as input, but that doesn't work:  $(env:WebServer)

**Comment by tanyabr** [comment]
Hi,
I would like to do the same but have the new variable available in other environments. Is this possible? If so - how?

Thanks,
Tanya.

**Comment by hcoona** [comment]
@chrisrpatterson This tricks only works for one-line varaible. I'd like to load copy file patterns from config file but it contains line-endings as seperator but be consumed in standard copy task in VSO. Is there a more powerful way for it?

**Comment by ericsciple** [comment]
you can replace carriage return and line feed with the URL encoded equivalents (`%0D%0A`)

**Comment by whihathac** [comment]
> This will make the variable available later in the build and it should be in your environment. 
Does this mean the variable will persist on other agent phases in the same Environment but different Agent Queues?

**Comment by iyerusad** [comment]
These variables do not appear to persist **across phases**, only _**tasks** within the same phase_.

Is there a method to have the variables persist across release phases? 

CC: @whihathac @chrisrpatterson et al.

**Comment by whihathac** [comment]
no clue, I am waiting for an answer too :)

**Comment by iyerusad** [comment]
@whihathac variables across phases has issue here: https://github.com/Microsoft/vsts-tasks/issues/4743

**Comment by sufyannisar** [comment]
I am using _Run PowerShell on Remote Machine From File_
I want to change variable value but
Whenever I use `Write-Host` in Powershell script I get error saying 

> A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.

**Comment by ederbond** [comment]
Me too @sufyannisar

**Comment by weznagwama** [comment]
I'd like to echo Tanya's question: are you able to set/update a variable inside a release, for use in another release?

Or, are you able to update the value of a variable inside of a shared variable group? This could perhaps be in the realm of the API, which I haven't yet looked at...

**Comment by cserkaran** [comment]
Is it possible to overwrite System variables e.g. $Env:SYSTEM_DEFAULTWORKINGDIRECTORY in the powershell script using Write-Host

**Comment by oleksabor** [comment]
I'm trying to set variable in the powerShell task and use in the next one but no luck

````
steps:
- powershell: |
   $fv = Get-Content versionFile
   Write-Host ("##vso[task.setvariable variable=versionFromFile]$fv")
   Write-Host ("fv=$fv versionFromFile=$versionFromFile")
  displayName: 'version from file'   
  
- powershell: |
   if ([string]::IsNullOrEmpty($versionFromFile)) { Throw New-Object System.ArgumentException([string]::Format("failed to read version")) }
````
There is exception on the second step `failed to read version`
First task output is `fv=0.7.3 versionFromFile=` so version was read properly.

Were there any changes in the `task.setvariable` ? I'm running build on https://dev.azure.com using private agent 2.152.1. Seems that it had been worked before update

**Comment by siljemda** [comment]
Is there any update on this? I have a global variable named "shouldBuild" with a standard value of "no" and an inline powershell script that uses a switch to check if there are changes. If so it runs the following line:
`Write-Host "hello"; Write-Output "##vso[task.setvariable variable=shouldBuild;isOutput=true]ding"`

And I can see "hello" being written to the log, but neither immediate write-host of the variable nor later logs in the pipeline display the new value ("ding") - the value is still "no".
